name: Build EXE with Nuitka

on: [push, release]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka zstandard sounddevice
        choco install upx
        
    - name: Build with Nuitka
      run: |
        nuitka --onefile --windows-disable-console --plugin-enable=sounddevice ^
        --include-data-file=C:/Windows/Fonts/seguiemj.ttf=seguiemj.ttf ^
        --remove-output --output-dir=dist virtual_mic.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualMic
        path: dist/virtual_mic.exe
        if-no-files-found: error
        
    - name: Create Release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/virtual_mic.exe
        tag_name: v0.1.${{ github.run_number }}
        draft: false
