name: Build VirtualMic

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install pyinstaller==5.13.0 sounddevice==0.4.6
        choco install -y upx
        
    - name: Build with PyInstaller
      shell: cmd
      run: |
        pyinstaller --onefile --windowed --clean ^
        --name VirtualMic ^
        virtual_mic.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualMic
        path: dist/VirtualMic.exe
