name: Build Windows Tray App

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install nuitka==1.8.6 zstandard sounddevice
        choco install -y mingw --version=12.2.0
        
    - name: Setup MinGW
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
        
    - name: Compile with Nuitka
      shell: cmd  # 关键修改：强制使用CMD而不是PowerShell
      run: |
        nuitka --mingw64 --standalone --onefile --windows-disable-console ^
         --plugin-enable=pylint-warnings --plugin-enable=tk-inter ^
         --include-data-file=C:/Windows/Fonts/seguiemj.ttf=seguiemj.ttf ^
         --include-package=PIL ^
         --output-dir=dist virtual_mic.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualMic_Tray
        path: dist/virtual_mic.exe
