name: Build Windows Tray App

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka==1.8.6 zstandard sounddevice
        choco install -y upx
        
    - name: Download Windows SDK
      run: |
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?linkid=2196241" -OutFile vs_BuildTools.exe
        Start-Process vs_BuildTools.exe -ArgumentList '--add Microsoft.VisualStudio.Workload.VCTools --quiet --norestart' -Wait
        
    - name: Compile with Nuitka
      run: |
        $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64"
        nuitka --mingw64 --onefile --windows-disable-console ^
          --plugin-enable=sounddevice ^
          --include-data-file=mic.ico=mic.ico ^
          --windows-icon-from-ico=mic.ico ^
          --output-dir=dist virtual_mic.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VirtualMic_Tray
        path: dist/virtual_mic.exe
